### ISSUE TITLE
libseven pkgbuild

### ISSUE THREAD

**Issue by maraflush** [LunarLambda/libseven#2]
Hello @LunarLambda,

Our discussion on libgba allowed me to see your **`libseven`** project.
Why don't you make a package so we can download your library already packaged ?

It's will be great, in my opinion.

Regards,

**Comment by LunarLambda** [comment]
I'm not too familiar with pkgbuild. Building libseven only requires `make` and `arm-none-eabi-gcc`, both already provided by devkitARM or even a standalone ARM toolchain, then the library can be integrated into the project by copying the file or linking it from the build directory. See `examples/template` for how to pull in libseven.

Besides, libseven is still in pre-1.0 development, so a lot of recompiles would be necessary. That said, I can look into it.

There's also the problem of finding the correct header include paths for installation. I think it may be /usr/include/arm-none-eabi/ but I don't know if devkitPRO uses it, or if it is entirely constrained to /opt. I can look into the libgba PKGBUILD and report back.

**Comment by maraflush** [comment]
I can create a first attempt of PKGBUILD. I already created for a personal source package.
It's really great effort to offer an alternative for the gba programming 👍

**Comment by maraflush** [comment]
I look : their PKGBUILD (devkitpro) built thanks to  a tarball file.
It's seems the PKGBUILD on archlinux can produce a package via git repository.

> There's also the problem of finding the correct header include paths for installation. I think it may be /usr/include/arm-none-eabi/ but I don't know if devkitPRO uses it, or if it is entirely constrained to /opt. I can look into the libgba PKGBUILD and report back.

Yes, I'm agree with you, It's a important point.

**Comment by maraflush** [comment]
I checked, the packages are installed in $(DESTDIR)/$(DEVKITPRO) by a target install in the Makefile provided by the library like `libgba`

**Comment by LunarLambda** [comment]
I've added a PKGBUILD in the style of libgba's/libtonc's that pulls the latest git version.

Let me know if this is what you wanted.

Note that `makepkg` will warn you about libseven.a containing references to `$srcdir`, this is because of the debugging information and to be expected.

[PKGBUILD](https://github.com/LunarLambda/libseven/blob/0f3de1bcafd65cc3977bc6b5388528689a91a2bd/pkgbuild/PKGBUILD)

**Comment by maraflush** [comment]
I will push on my repo for proposal a PKGBUILD soon :) to discuss

**Comment by LunarLambda** [comment]
discuss what?

I followed the archlinux PKGBUILD guidelines closely, I don't see anything wrong with the way I wrote it

I will add a 'stable' PKGBUILD using the latest git release tag once libseven officially hits 1.0 and I put proper versioning into place.

**Comment by maraflush** [comment]
I've created a pkgbuild with your git code.
I'm not sure for some elements like version, etc etc.
https://github.com/maraflush/pacman-packages/blob/libseven-package/libseven/PKGBUILD

By the way to compile the package, you need to use :
```bash
dkp-makepkg
```

to install the package in your devkitpro base :

```bash
sudo dkp-pacman -U libseven-0.1-1-any.pkg.tar.xz
```

or 

```bash
dkp-pacman -U libseven-0.1-1-any.pkg.tar.xz
```

**Comment by maraflush** [comment]
Ok :)

**Comment by LunarLambda** [comment]
This looks to be largely identical to mine, minus the fact the install part is hoisted out of the Makefile.

See my comments about versioning and using the `-git` suffix though.

The licenses don't need to be installed, because right now documentation isn't installed (structure is still subject to change, and many parts are outdated at this point), and the licenses (MPL2, CC0) are part of the standard `licenses` package anyway.

If you have no other concerns I will close this now. Have you tried using my PKGBUILD? Process is the same as yours.

**Comment by maraflush** [comment]
Hello, 
The depends with git stop the package creation.
And the makepkg seems doesn't like a stuff :
```
==> Création du paquet libseven-git r138.e2479f0-1 (Lun 27 déc 2021 13:29:50 CET)
==> Vérification des dépendances pour l’exécution...
==> Vérification des dépendances pour la compilation...
==> Récupération des sources...
  -> Clonage du dépôt libseven git...
Clonage dans le dépôt nu '/Users/mara/poipi/ppppp/pacman-packages/libseven/libseven'
remote: Enumerating objects: 833, done.
remote: Counting objects: 100% (833/833), done.
remote: Compressing objects: 100% (527/527), done.
remote: Total 833 (delta 540), reused 560 (delta 268), pack-reused 0
Réception d'objets: 100% (833/833), 212.80 Kio | 648.00 Kio/s, fait.
Résolution des deltas: 100% (540/540), fait.
==> Validation des fichiers source avec md5sums...
    libseven ... Ignoré
==> Extraction des sources...
  -> Création d’une copie de travail du dépot libseven git...
Clonage dans 'libseven'...
fait.
==> Lancement de pkgver()...
sed: 1: "/Users/mara/poipi/pppp ...": undefined label 'mara/poipi/ppppp/pacman-packages/libseven/PKGBUILD'
==> ERREUR : Échec de la mise à jour de pkgver de la version r138.e2479f0 à la version r139.0f3de1b
```

**Comment by LunarLambda** [comment]
I don't understand french. The only thing I can make out is that it doesn't like the pkgver?

Please try if you can get English output with `LANG=en dkp-makepkg -s`?

**Comment by maraflush** [comment]
Yes of course.

**Comment by maraflush** [comment]
```
==> Making package: libseven-git r138.e2479f0-1 (Mon Dec 27 13:38:27 CET 2021)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> Retrieving sources...
  -> Cloning libseven git repo...
Cloning into bare repository '/Users/mara/poipi/ppppp/pacman-packages/libseven/libseven'...
remote: Enumerating objects: 833, done.
remote: Counting objects: 100% (833/833), done.
remote: Compressing objects: 100% (527/527), done.
remote: Total 833 (delta 540), reused 560 (delta 268), pack-reused 0
Receiving objects: 100% (833/833), 212.80 KiB | 644.00 KiB/s, done.
Resolving deltas: 100% (540/540), done.
==> Validating source files with md5sums...
    libseven ... Skipped
==> Extracting sources...
  -> Creating working copy of libseven git repo...
Cloning into 'libseven'...
done.
==> Starting pkgver()...
sed: 1: "/Users/mara/poipi/pppp ...": undefined label 'mara/poipi/ppppp/pacman-packages/libseven/PKGBUILD'
==> ERROR: Failed to update pkgver from r138.e2479f0 to r139.0f3de1b

**Comment by LunarLambda** [comment]
It seems to be a problem with the `sed` command on MacOS requiring different syntax.
I can't help you there, that's something to report to https://github.com/devkitpro/pacman.

See https://mkyong.com/mac/sed-command-hits-undefined-label-error-on-mac-os-x/.

You might also be able to prevent the automatic version bump using the `--holdver` option of `makepkg`

**Comment by maraflush** [comment]
I've the solution.
This file built correctly :
```
pkgname='libseven-git'
pkgver=r138.e2479f0
pkgrel=1
pkgdesc='from-scratch library for GBA development'
arch=('any')
url='https://github.com/LunarLambda/libseven'
license=('MPL2')
groups=('gba-dev')
depends=('devkitARM' 'devkitarm-rules' 'devkitarm-crtls')
provides=('libseven')
conflicts=('libseven')
options=('!strip' 'libtool' 'staticlibs')
source=('libseven::git+https://github.com/LunarLambda/libseven')
md5sums=('SKIP')

build() {
    make -C libseven -f Makefile.dkp
}

package() {
    make -C libseven -f Makefile.dkp DESTDIR=$pkgdir install
}
```

**Comment by LunarLambda** [comment]
You can't remove `git` from the `makedepends`, since the source is a git repository.

Also removing the versioning is an equally bad idea. Did you try using `--holdver`?

**Comment by maraflush** [comment]
* If I keep the `makedepends('git')` : 
```
LANG=C dkp-makepkg --holdver
==> Making package: libseven-git r138.e2479f0-1 (Mon Dec 27 14:28:03 CET 2021)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> Missing dependencies:
  -> git
==> ERROR: Could not resolve all dependencies.
```
* without `git` dependency :
```
LANG=C dkp-makepkg --holdver
==> Making package: libseven-git r138.e2479f0-1 (Mon Dec 27 14:30:13 CET 2021)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> Retrieving sources...
  -> Cloning libseven git repo...
Cloning into bare repository '/Users/mara/poipi/ppppp/pacman-packages/libseven/libseven'...
remote: Enumerating objects: 833, done.
remote: Counting objects: 100% (833/833), done.
remote: Compressing objects: 100% (527/527), done.
remote: Total 833 (delta 540), reused 560 (delta 268), pack-reused 0
Receiving objects: 100% (833/833), 212.80 KiB | 644.00 KiB/s, done.
Resolving deltas: 100% (540/540), done.
==> Validating source files with md5sums...
    libseven ... Skipped
==> Extracting sources...
  -> Creating working copy of libseven git repo...
Cloning into 'libseven'...
done.
==> Starting pkgver()...
sed: 1: "/Users/mara/poipi/pppp ...": undefined label 'ento/poipi/ppppp/pacman-packages/libseven/PKGBUILD'
==> ERROR: Failed to update pkgver from r138.e2479f0 to r139.0f3de1b
```

**Comment by LunarLambda** [comment]
`-d` skips dependency checks, you can use that.

This PKGBUILD is for MSYS2 and Linux systems like Arch and Manjaro that use `pacman` as their standard package manager.

I don't think there is a *proper* way to release PKGBUILDS for `dkp-pacman`, since versioning and proper dependency specification both go out the window, either because of operating-specific things like MacOS `sed`, or because `dkp-pacman` relies on tools like `git`, `make`, etc. existing somewhere else on the system.

You are free to use your own `PKGBUILD` for installing libseven globally, but as I see it there isn't a whole lot I can do to help without breaking all of the rules.

**Comment by maraflush** [comment]
I'm understanding your point of view but it is sad to block the osx user to build the package.
I'm closing the issue if you are agree.

**Comment by LunarLambda** [comment]
Did you try `-d --holdver`? If I understood, that should solve the two problems you're having (version bump and git dependency check).

I don't like blocking out non-standard configurations but it's also not in my hands.

**Comment by maraflush** [comment]
Looks :) :
```
LANG=C dkp-makepkg -f -d --holdver
==> Making package: libseven-git r138.e2479f0-1 (Mon Dec 27 14:46:24 CET 2021)
==> WARNING: Skipping dependency checks.
==> Retrieving sources...
==> Validating source files with md5sums...
    libseven ... Skipped
==> Extracting sources...
  -> Creating working copy of libseven git repo...
Reset branch 'makepkg'
==> Starting pkgver()...
sed: 1: "/Users/mara/poipi/pppp ...": undefined label 'mara/poipi/ppppp/pacman-packages/libseven/PKGBUILD'
==> ERROR: Failed to update pkgver from r138.e2479f0 to r139.0f3de1b

**Comment by LunarLambda** [comment]
I see. Report it to https://github.com/devkitPro/pacman as a MacOS issue or install with `make install` or remove the `pkgver()` part and install it your way.

Otherwise, this is a wontfix from me, apologies.
Note that a future stable libseven package won't have this problem, this is specific to the `-git` versioning.

I will make sure to include a note for MacOS users in the documentation when I add it.

Have a nice day.

**Comment by maraflush** [comment]
:-)
Have a nice day.
