### ISSUE TITLE
.include assembler macro not working for Arm GNU Toolchain Version 11.2-2022.02

### ISSUE THREAD

**Issue by felixjones** [LunarLambda/libseven#4]
The `.include` macro is currently broken in Arm GNU Toolchain Version 11.2-2022.02, which has affected libseven:
```
seven/src/hw/input.s:10: Error: can't open macros.s for reading: No such file or directory
seven/src/hw/input.s:11: Error: can't open seven/asm/hw/input.s for reading: No such file or directory
```

For my own things I have worked around this by instead using the C pre-processor `#include` macro, which requires assembling with the `-x assembler-with-cpp` flag.
Kind of gross using C pre-processor when assembler macros traditionally exist (and work), I liked that libseven kept things pure, but alas, Arm GNU Toolchain broke it.

**Comment by LunarLambda** [comment]
I'll see what I can figure out. I've already heard that the new toolchain also has other broken search path issues, so I may need to write this off as wontfix. Not sure

**Comment by exelotl** [comment]
There is a ticket for it here: https://bugs.linaro.org/show_bug.cgi?id=5835
And accompanying forum post: https://community.arm.com/support-forums/f/compilers-and-libraries-forum/52288/arm-none-eabi-gcc-11-version-compiler-asmbler-failed

Suggested fixes include spec file tweaks, or simply passing `-Wa,-Iinc` to gcc.

**Comment by felixjones** [comment]
I can confirm that explicitly passing `-Wa,-I*full/path/to/seven/include -Wa,-I*full/path/to/seven/src*` works

**Comment by LunarLambda** [comment]
Does it have to be a full path? Or in other words, does https://github.com/LunarLambda/libseven/commit/ed13c581444f0a158d06b9341abd90d18a00d1ce fix the Makefile?

**Comment by felixjones** [comment]
> Does it have to be a full path? Or in other words, does [ed13c58](https://github.com/LunarLambda/libseven/commit/ed13c581444f0a158d06b9341abd90d18a00d1ce) fix the Makefile?

Tested, yes this commit fixes it for Makefile with Arm GNU Toolchain Version 11.2-2022.02

Thanks loads!

**Comment by LunarLambda** [comment]
Thank you. Will push a fix tomorrow. Good night
